trigger:
- main

schedules:
- cron: "*/5 * * * *"   # This cron expression runs the pipeline every 5 minutes
  displayName: "Run every 5 minutes"
  branches:
    include:
    - main   # You can specify other branches if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt  # If you have any Python dependencies

    python Demo.py  # Replace with your Python script path
  displayName: 'Run Python script'
